package dev.nheggoe
package aoc25

import dev.nheggoe.aoc.Input
import munit.FunSuite

class Day07Test extends FunSuite {

  private val input = """.......S.......
                        |...............
                        |.......^.......
                        |...............
                        |......^.^......
                        |...............
                        |.....^.^.^.....
                        |...............
                        |....^.^...^....
                        |...............
                        |...^.^...^.^...
                        |...............
                        |..^...^.....^..
                        |...............
                        |.^.^.^.^.^...^.
                        |...............""".stripMargin
  given Input = input

  test("Part one") {
    val expected = 21L
    assertEquals(Day07.partOne, expected)
  }

  test("part two") {
    val expected = 40L
    assertEquals(Day07.partTwo, expected)
  }
}
