package dev.nheggoe
package aoc25

import munit.FunSuite

class Day07Test extends FunSuite {

  private val input = """.......S.......
                        |...............
                        |.......^.......
                        |...............
                        |......^.^......
                        |...............
                        |.....^.^.^.....
                        |...............
                        |....^.^...^....
                        |...............
                        |...^.^...^.^...
                        |...............
                        |..^...^.....^..
                        |...............
                        |.^.^.^.^.^...^.
                        |...............""".stripMargin

  test("Part one") {
    val expected = 21
    assertEquals(Day07.partOne(input), expected)
  }
}
